name: master

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  # Static analysis, and documentation build
  lint:
    name: Linters, licenses, dependencies and documentation generation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Spark repository
      uses: actions/checkout@v2
    - name: Lint Code Base
      uses: docker://github/super-linter:v3
      env:
        DEFAULT_BRANCH: master
        VALIDATE_MD: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
